from __future__ import annotations

from .models import DatasetSource


def _dataset_source(
    *,
    source_id: str,
    source_type: str,
    entrypoint: str,
    version: str,
    license: str,
    language: str,
    market_scope: str,
    task_types: tuple[str, ...],
    quality_score: float,
    allow_training: bool,
    allow_translation: bool,
    enabled_by_default: bool,
) -> DatasetSource:
    return DatasetSource(
        source_id=source_id,
        source_type=source_type,
        entrypoint=entrypoint,
        version=version,
        license=license,
        language=language,
        market_scope=market_scope,
        task_types=task_types,
        quality_score=quality_score,
        allow_training=allow_training,
        allow_translation=allow_translation,
        enabled_by_default=enabled_by_default,
    )


def build_default_dataset_registry() -> tuple[DatasetSource, ...]:
    return (
        _dataset_source(
            source_id="cflue",
            source_type="github_repo",
            entrypoint="https://github.com/aliyun/cflue",
            version="master",
            license="CC-BY-NC-SA-4.0",
            language="zh",
            market_scope="finance_global",
            task_types=("classification", "qa"),
            quality_score=0.95,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="fiqa",
            source_type="huggingface_dataset",
            entrypoint="BeIR/fiqa",
            version="default",
            license="cc-by-sa-4.0",
            language="en",
            market_scope="finance_global",
            task_types=("retrieval", "qrels"),
            quality_score=0.9,
            allow_training=True,
            allow_translation=True,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="finfe",
            source_type="huggingface_dataset",
            entrypoint="FinanceMTEB/FinFE",
            version="default",
            license="research",
            language="zh",
            market_scope="finance_global",
            task_types=("classification",),
            quality_score=0.94,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="chnsenticorp",
            source_type="huggingface_dataset",
            entrypoint="lansinuote/ChnSentiCorp",
            version="default",
            license="open",
            language="zh",
            market_scope="finance_global",
            task_types=("classification",),
            quality_score=0.9,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="fin_news_sentiment",
            source_type="github_repo",
            entrypoint="https://github.com/wwwxmu/Dataset-of-financial-news-sentiment-classification",
            version="master",
            license="open",
            language="zh",
            market_scope="finance_global",
            task_types=("classification",),
            quality_score=0.89,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="msra_ner",
            source_type="huggingface_dataset",
            entrypoint="levow/msra_ner",
            version="default",
            license="research",
            language="zh",
            market_scope="finance_global",
            task_types=("entity_crf",),
            quality_score=0.93,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="peoples_daily_ner",
            source_type="huggingface_dataset",
            entrypoint="peoples_daily_ner",
            version="default",
            license="research",
            language="zh",
            market_scope="finance_global",
            task_types=("entity_crf",),
            quality_score=0.88,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="cluener",
            source_type="github_repo",
            entrypoint="https://github.com/CLUEbenchmark/CLUENER2020",
            version="master",
            license="open",
            language="zh",
            market_scope="finance_global",
            task_types=("entity_crf",),
            quality_score=0.91,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="tnews",
            source_type="huggingface_dataset",
            entrypoint="clue/clue",
            version="tnews",
            license="open",
            language="zh",
            market_scope="finance_global",
            task_types=("classification",),
            quality_score=0.87,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="thucnews",
            source_type="direct_http",
            entrypoint="https://ndownloader.figshare.com/files/51924092",
            version="THUCNews1.7z",
            license="research",
            language="zh",
            market_scope="finance_global",
            task_types=("classification", "intent"),
            quality_score=0.86,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="finnl",
            source_type="github_repo",
            entrypoint="https://github.com/ssymmetry/BBT-FinCUGE-Applications",
            version="main",
            license="research",
            language="zh",
            market_scope="finance_global",
            task_types=("classification", "topic"),
            quality_score=0.87,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="mxode_finance",
            source_type="huggingface_dataset",
            entrypoint="Mxode/IndustryInstruction-Chinese",
            version="default",
            license="apache-2.0",
            language="zh",
            market_scope="finance_global",
            task_types=("classification", "intent", "topic"),
            quality_score=0.9,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="baai_finance_instruction",
            source_type="huggingface_dataset",
            entrypoint="BAAI/IndustryInstruction_Finance-Economics",
            version="default",
            license="apache-2.0",
            language="zh_en",
            market_scope="finance_global",
            task_types=("classification", "intent", "topic"),
            quality_score=0.91,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="qrecc",
            source_type="huggingface_dataset",
            entrypoint="slupart/qrecc",
            version="default",
            license="research",
            language="en",
            market_scope="general",
            task_types=("classification", "qa"),
            quality_score=0.86,
            allow_training=True,
            allow_translation=True,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="naturalconv",
            source_type="huggingface_dataset",
            entrypoint="xywang1/NaturalConv",
            version="default",
            license="research",
            language="zh",
            market_scope="general",
            task_types=("classification", "dialogue"),
            quality_score=0.85,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="dailydialog",
            source_type="huggingface_dataset",
            entrypoint="roskoN/dailydialog",
            version="default",
            license="cc-by-nc-sa-4.0",
            language="en",
            market_scope="general",
            task_types=("classification", "dialogue"),
            quality_score=0.84,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="risawoz",
            source_type="huggingface_dataset",
            entrypoint="GEM/RiSAWOZ",
            version="default",
            license="cc-by-4.0",
            language="zh",
            market_scope="general",
            task_types=("classification", "dialogue"),
            quality_score=0.86,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="t2ranking",
            source_type="huggingface_dataset",
            entrypoint="THUIR/T2Ranking",
            version="default",
            license="research",
            language="zh",
            market_scope="finance_global",
            task_types=("retrieval", "qrels"),
            quality_score=0.9,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="fincprg",
            source_type="huggingface_dataset",
            entrypoint="valuesimplex-ai-lab/FinCPRG",
            version="default",
            license="apache-2.0",
            language="zh",
            market_scope="finance_global",
            task_types=("retrieval", "qrels"),
            quality_score=0.93,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="fir_bench_reports",
            source_type="huggingface_dataset",
            entrypoint="valuesimplex-ai-lab/FIR-Bench-Research-Reports-FinQA",
            version="default",
            license="apache-2.0",
            language="zh",
            market_scope="finance_global",
            task_types=("retrieval", "qrels"),
            quality_score=0.92,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="fir_bench_announcements",
            source_type="huggingface_dataset",
            entrypoint="valuesimplex-ai-lab/FIR-Bench-Announcements-FinQA",
            version="default",
            license="apache-2.0",
            language="zh",
            market_scope="finance_global",
            task_types=("retrieval", "qrels"),
            quality_score=0.92,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="csprd",
            source_type="github_repo",
            entrypoint="https://github.com/noewangjy/csprd_dataset",
            version="main",
            license="research",
            language="zh",
            market_scope="finance_global",
            task_types=("retrieval", "qrels"),
            quality_score=0.84,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
        _dataset_source(
            source_id="smp2017",
            source_type="github_repo",
            entrypoint="https://github.com/HITlilingzhi/SMP2017ECDT-DATA",
            version="master",
            license="research",
            language="zh",
            market_scope="finance_global",
            task_types=("classification", "intent"),
            quality_score=0.83,
            allow_training=True,
            allow_translation=False,
            enabled_by_default=True,
        ),
    )


def resolve_enabled_sources(registry: tuple[DatasetSource, ...], settings) -> list[DatasetSource]:
    if not settings.enable_external_data:
        return []
    allowlist = set(settings.dataset_allowlist)
    enabled = [item for item in registry if item.enabled_by_default]
    if allowlist:
        enabled = [item for item in enabled if item.source_id in allowlist]
    return enabled
